In [1]:
import torch

In [2]:
X = torch.randn(3,requires_grad=True)

In [3]:
X

tensor([ 0.3891, -0.2005, -0.2464], requires_grad=True)

In [4]:
y = X + 2

In [5]:
y

tensor([2.3891, 1.7995, 1.7536], grad_fn=<AddBackward0>)

In [6]:
z = y*y*2

In [7]:
z

tensor([11.4156,  6.4761,  6.1502], grad_fn=<MulBackward0>)

In [8]:
v = torch.tensor([0.1,1.0,0.001],dtype=torch.float32)

In [9]:
z.backward(v)

In [10]:
X.grad

tensor([9.5564e-01, 7.1978e+00, 7.0144e-03])

In [11]:
z

tensor([11.4156,  6.4761,  6.1502], grad_fn=<MulBackward0>)

In [12]:
X = torch.randn(3,requires_grad=True)

In [13]:
X

tensor([ 0.3316, -2.1486,  0.0645], requires_grad=True)

In [14]:
X.requires_grad_(False)

tensor([ 0.3316, -2.1486,  0.0645])

In [15]:
X.detach()

tensor([ 0.3316, -2.1486,  0.0645])

In [16]:
with torch.no_grad():
    print(X)

tensor([ 0.3316, -2.1486,  0.0645])


In [17]:
weights = torch.ones(4,requires_grad=True)
for epoch in range(3):
    model_output = (weights*3).sum()
    print(model_output)
    model_output.backward()
    print(weights.grad)
    weights.grad.zero_()

tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])


In [18]:
weights.grad.zero_()

tensor([0., 0., 0., 0.])

In [19]:
weights

tensor([1., 1., 1., 1.], requires_grad=True)

In [20]:
import torch

In [21]:
x = torch.tensor(1.0)

In [22]:
y = torch.tensor(2.0)

In [23]:
w = torch.tensor(1.0,requires_grad=True)

In [24]:
y_hat = w * x
loss = (y_hat - y)**2

In [25]:
loss

tensor(1., grad_fn=<PowBackward0>)

In [26]:
loss.backward(retain_graph=False)

In [27]:
w.grad

tensor(-2.)

In [28]:
import numpy as np

In [29]:
# f = w * x
# f = 2 * x
X = np.array([1,2,3,4],dtype=np.float32)

In [30]:
Y = np.array([1*2,2*2,3*2,4*2],dtype=np.float32)

In [31]:
w = 0.0

In [32]:
# model preds
def forward(x):
    return w * x

In [33]:
# loss = MSE
def loss(y,y_preds):
    return ((y_preds-y)**2).mean()

In [34]:
# gradient
# MSE = 1/N * (w * x - y)**2
def gradient(x,y,y_preds):
    return np.dot(2*x,y_preds-y).mean()

In [35]:
print(f'Preds before Training : f(5) = {forward(5):.3f}')

Preds before Training : f(5) = 0.000


In [36]:
learning_rate = 0.01
n_iters = 2500

In [37]:
for epoch in range(n_iters):
    # preds = forward pass
    y_preds = forward(X)
    # loss
    l = loss(Y,y_preds)
    # gradients
    dw = gradient(X,Y,y_preds)
    # update weights
    w -= learning_rate * dw
    print(dw)
    print(f'Epoch : {epoch+1} Weight : {w:.3f} Loss = {l:.8f}')

-120.0
Epoch : 1 Weight : 1.200 Loss = 30.00000000
-47.999996
Epoch : 2 Weight : 1.680 Loss = 4.79999924
-19.200003
Epoch : 3 Weight : 1.872 Loss = 0.76800019
-7.68
Epoch : 4 Weight : 1.949 Loss = 0.12288000
-3.0720026
Epoch : 5 Weight : 1.980 Loss = 0.01966083
-1.2288015
Epoch : 6 Weight : 1.992 Loss = 0.00314574
-0.49151587
Epoch : 7 Weight : 1.997 Loss = 0.00050331
-0.1966095
Epoch : 8 Weight : 1.999 Loss = 0.00008053
-0.07864165
Epoch : 9 Weight : 1.999 Loss = 0.00001288
-0.031455517
Epoch : 10 Weight : 2.000 Loss = 0.00000206
-0.012580633
Epoch : 11 Weight : 2.000 Loss = 0.00000033
-0.0050354004
Epoch : 12 Weight : 2.000 Loss = 0.00000005
-0.0020184517
Epoch : 13 Weight : 2.000 Loss = 0.00000001
-0.0008010864
Epoch : 14 Weight : 2.000 Loss = 0.00000000
-0.00032258034
Epoch : 15 Weight : 2.000 Loss = 0.00000000
-0.00013017654
Epoch : 16 Weight : 2.000 Loss = 0.00000000
-4.9352646e-05
Epoch : 17 Weight : 2.000 Loss = 0.00000000
-2.0742416e-05
Epoch : 18 Weight : 2.000 Loss = 0.00000

In [38]:
print(f'Preds before Training : f(5) = {forward(5):.3f}')

Preds before Training : f(5) = 10.000


In [39]:
import torch
# Compute every step manually

# Linear regression
# f = w * x 

# here : f = 2 * x
X = torch.tensor([1, 2, 3, 4], dtype=torch.float32)
Y = torch.tensor([2, 4, 6, 8], dtype=torch.float32)

w = torch.tensor(0.0,dtype=torch.float32,requires_grad=True)

# model output
def forward(x):
    return w * x

# loss = MSE
def loss(y, y_pred):
    return ((y_pred - y)**2).mean()

print(f'Prediction before training: f(5) = {forward(5):.3f}')

# Training
learning_rate = 0.01
n_iters = 75

for epoch in range(n_iters):
    # predict = forward pass
    y_pred = forward(X)

    # loss
    l = loss(Y, y_pred)
    
    # calculate gradients
    l.backward()

    # update weights
    with torch.no_grad():
        w -= learning_rate * w.grad
    w.grad.zero_()
    if epoch % 2 == 0:
        print(f'epoch {epoch+1}: w = {w:.3f}, loss = {l:.8f}')
     
print(f'Prediction after training: f(5) = {forward(5):.3f}')

Prediction before training: f(5) = 0.000
epoch 1: w = 0.300, loss = 30.00000000
epoch 3: w = 0.772, loss = 15.66018772
epoch 5: w = 1.113, loss = 8.17471695
epoch 7: w = 1.359, loss = 4.26725292
epoch 9: w = 1.537, loss = 2.22753215
epoch 11: w = 1.665, loss = 1.16278565
epoch 13: w = 1.758, loss = 0.60698116
epoch 15: w = 1.825, loss = 0.31684780
epoch 17: w = 1.874, loss = 0.16539653
epoch 19: w = 1.909, loss = 0.08633806
epoch 21: w = 1.934, loss = 0.04506890
epoch 23: w = 1.952, loss = 0.02352631
epoch 25: w = 1.966, loss = 0.01228084
epoch 27: w = 1.975, loss = 0.00641066
epoch 29: w = 1.982, loss = 0.00334642
epoch 31: w = 1.987, loss = 0.00174685
epoch 33: w = 1.991, loss = 0.00091188
epoch 35: w = 1.993, loss = 0.00047601
epoch 37: w = 1.995, loss = 0.00024848
epoch 39: w = 1.996, loss = 0.00012971
epoch 41: w = 1.997, loss = 0.00006770
epoch 43: w = 1.998, loss = 0.00003534
epoch 45: w = 1.999, loss = 0.00001845
epoch 47: w = 1.999, loss = 0.00000963
epoch 49: w = 1.999, loss 

In [40]:
import torch
import torch.nn as nn
# Here we replace the manually computed gradient with autograd

# Linear regression
# f = w * x 

# here : f = 2 * x
X = torch.tensor([1, 2, 3, 4], dtype=torch.float32)
Y = torch.tensor([2, 4, 6, 8], dtype=torch.float32)

w = torch.tensor(0.0, dtype=torch.float32, requires_grad=True)

# model output
def forward(x):
    return w * x

print(f'Prediction before training: f(5) = {forward(5).item():.3f}')

# Training
learning_rate = 0.01
n_iters = 100
loss = nn.MSELoss()
optimizer = torch.optim.SGD([w],lr=learning_rate)

for epoch in range(n_iters):
    # predict = forward pass
    y_pred = forward(X)

    # loss
    l = loss(Y, y_pred)

    # calculate gradients = backward pass
    l.backward()

    # update weights
    optimizer.step()
    
    # zero the gradients after updating
    optimizer.zero_grad()

    print(f'Prediction after training: f(5) = {forward(5).item():.3f}')

Prediction before training: f(5) = 0.000
Prediction after training: f(5) = 1.500
Prediction after training: f(5) = 2.775
Prediction after training: f(5) = 3.859
Prediction after training: f(5) = 4.780
Prediction after training: f(5) = 5.563
Prediction after training: f(5) = 6.229
Prediction after training: f(5) = 6.794
Prediction after training: f(5) = 7.275
Prediction after training: f(5) = 7.684
Prediction after training: f(5) = 8.031
Prediction after training: f(5) = 8.327
Prediction after training: f(5) = 8.578
Prediction after training: f(5) = 8.791
Prediction after training: f(5) = 8.972
Prediction after training: f(5) = 9.126
Prediction after training: f(5) = 9.257
Prediction after training: f(5) = 9.369
Prediction after training: f(5) = 9.464
Prediction after training: f(5) = 9.544
Prediction after training: f(5) = 9.612
Prediction after training: f(5) = 9.671
Prediction after training: f(5) = 9.720
Prediction after training: f(5) = 9.762
Prediction after training: f(5) = 9.798

In [41]:
# Design the model
# Make the loss and optimizr
# Training loop
# - forward pass : predict
# - backward pass : the loss with change its gradients
# - update weights : with the gradients of the loss funtion the optimizer will change its parameters (models)

In [42]:
import torch
import torch.nn as nn
# Here we replace the manually computed gradient with autograd

# Linear regression
# f = w * x 

# here : f = 2 * x
X = torch.tensor([[1], [2], [3], [4]], dtype=torch.float32)
Y = torch.tensor([[2], [4], [6], [8]], dtype=torch.float32)
X_test = torch.tensor([5],dtype=torch.float32)
n_samples,n_features = X.shape
input_size = n_features
output_size = n_features

class LinearRegreession(nn.Module):
    def __init__(self,input_size,output_size):
        super().__init__()
        # define layers
        self.lin = nn.Linear(input_size,output_size)
        
    def forward(self,x):
        return self.lin(x)

model = LinearRegreession(input_size,output_size)
    
print(f'Prediction before training: f(5) = {model(X_test).item():.3f}')

# Training
learning_rate = 0.1
n_iters = 250
loss = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(),lr=learning_rate)

for epoch in range(n_iters):
    # predict = forward pass
    y_pred = model(X)

    # loss
    l = loss(Y, y_pred)

    # calculate gradients = backward pass
    l.backward()

    # update weights
    optimizer.step()
    
    # zero the gradients after updating
    optimizer.zero_grad()
    
    [w,b] = model.parameters()

    print(f'Prediction while training: f(5) = {model(X_test).item():.3f}')
print(f'Prediction after training: f(5) = {model(X_test).item():.3f}')

Prediction before training: f(5) = 2.731
Prediction while training: f(5) = 14.347
Prediction while training: f(5) = 6.580
Prediction while training: f(5) = 11.800
Prediction while training: f(5) = 8.317
Prediction while training: f(5) = 10.665
Prediction while training: f(5) = 9.105
Prediction while training: f(5) = 10.164
Prediction while training: f(5) = 9.467
Prediction while training: f(5) = 9.947
Prediction while training: f(5) = 9.638
Prediction while training: f(5) = 9.857
Prediction while training: f(5) = 9.722
Prediction while training: f(5) = 9.823
Prediction while training: f(5) = 9.766
Prediction while training: f(5) = 9.815
Prediction while training: f(5) = 9.792
Prediction while training: f(5) = 9.817
Prediction while training: f(5) = 9.810
Prediction while training: f(5) = 9.824
Prediction while training: f(5) = 9.824
Prediction while training: f(5) = 9.833
Prediction while training: f(5) = 9.836
Prediction while training: f(5) = 9.842
Prediction while training: f(5) = 9