In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.9.1


In [2]:
torch.device('cuda')

device(type='cuda')

In [3]:
!nvidia-smi

Sat Jul  8 09:46:48 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:26:00.0  On |                  N/A |
| 57%   54C    P2    47W / 170W |   2435MiB / 12288MiB |     39%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

## Introduction to Tensors

### Creating tensors

In [4]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim # finding the no. of dimentions

0

In [6]:
scalar.item() # just get the data in the tensor

7

In [8]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
# Matrix
MATRIX = torch.tensor(
    [
        [7,8],
        [8,9]
    ]
)

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
MATRIX.ndim

2

In [14]:
# Tensor

TENSOR = torch.tensor([[[1,2,3,4],[5,6,5,4],[6,8,9,4]]])

In [15]:
TENSOR

tensor([[[1, 2, 3, 4],
         [5, 6, 5, 4],
         [6, 8, 9, 4]]])

In [16]:
TENSOR.shape # first dimension, second is row, third is element in row

torch.Size([1, 3, 4])

In [17]:
TENSOR.ndim

3

In [18]:
TENSOR[0][2]

tensor([6, 8, 9, 4])

### Random Tensor

Why Random Tensors?
This stf is important becz the way many neural networks learn is that they start with tensors full of random numbers and the adjust those random numbers to better represent the data

`Start with random Numbers -> Look at data -> update random numbers -> look at data
Update the output data`

In [19]:
rdm_tensor = torch.rand(3,4) # rows, columns

In [20]:
rdm_tensor.shape

torch.Size([3, 4])

In [21]:
rdm_tensor.ndim

2

In [22]:
rdm_tensor

tensor([[0.4610, 0.9728, 0.4959, 0.9452],
        [0.8538, 0.9498, 0.1322, 0.0813],
        [0.2930, 0.9809, 0.6850, 0.6469]])

In [23]:
# Create random tensor with similar shape to image tensor
random_image_size_tensor = torch.rand(size=(3,484,224)) # height, width, color
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([3, 484, 224]), 3)

In [24]:
len(random_image_size_tensor[0]),len(random_image_size_tensor[1])

(484, 484)

### Tensors with ones and zeros

In [25]:
ones_tensor = torch.ones(3,4)
ones_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [26]:
zeros_tensor = torch.zeros(3,4)
zeros_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
rdm_tensor * zeros_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
ones_tensor.dtype

torch.float32

### Range

In [29]:
one_to_ten = torch.arange(start=1,end=11,step=1)

In [30]:
one_to_ten


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
ten_zeros = torch.zeros_like(input=one_to_ten)

In [32]:
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

In [33]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype=None,device='cuda',requires_grad=True)
float_32_tensor
# lower the bit no. the faster the data can be proccessed
# requires_grad means whther or not ot track the tensors gradient

tensor([3., 6., 9.], device='cuda:0', requires_grad=True)

In [34]:
float_32_tensor.dtype

torch.float32

In [35]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [36]:
float_16_tensor

tensor([3., 6., 9.], device='cuda:0', dtype=torch.float16,
       grad_fn=<CopyBackwards>)

In [37]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.], device='cuda:0', grad_fn=<MulBackward0>)

## Geting infor from tensor

Datatype - `tensor.dtype`

Shape - `tensor.shape`

Device - `tensor.device`

In [38]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.1329, 0.4664, 0.5542, 0.7325],
        [0.6650, 0.8874, 0.8003, 0.1305],
        [0.0612, 0.3378, 0.3317, 0.1508]])

In [39]:
print(some_tensor)
print(some_tensor.dtype)
print(some_tensor.size())
print(some_tensor.device)

tensor([[0.1329, 0.4664, 0.5542, 0.7325],
        [0.6650, 0.8874, 0.8003, 0.1305],
        [0.0612, 0.3378, 0.3317, 0.1508]])
torch.float32
torch.Size([3, 4])
cpu


# Manipulating Tensors

Tensor operations include:

- Addition
- Subtraction
- Multiplication (Element wise)
- Division
- Matrix Multiplication

In [40]:
# Addition

tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [41]:
# Multiplication

tensor * 10

tensor([10, 20, 30])

In [42]:
# Subtraction

tensor - 10

tensor([-9, -8, -7])

In [43]:
# Division

tensor / 1.5

tensor([0.6667, 1.3333, 2.0000])

In [44]:
# Torch builtin functions

torch.mul(tensor,10)
torch.div(tensor,1.5)
torch.add(tensor,10)
torch.subtract(tensor,10)

tensor([-9, -8, -7])

### Matrix multiplication

Two main ways to perform multiplication in neural networks and deep learning:
    
    1. Element Wise Multiplication
    2. Matrix Multiplication
    
2 Rules when doing matrix multiplication 

1. The inner dimmensions must match
* (3,2) * (2,3) [This works]
* (2,3) * (2,3) [Wont work]

2. The out put matrix is of the outer dimensions
* `(2,3) @ (3,2)` the output is (2,2)

In [45]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 114 µs, sys: 50 µs, total: 164 µs
Wall time: 145 µs


tensor(14)

In [46]:
tensor*tensor

tensor([1, 4, 9])

In [47]:
tensor

tensor([1, 2, 3])

In [48]:
%%time
# Matricx multiplication by hadnd
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]

CPU times: user 475 µs, sys: 0 ns, total: 475 µs
Wall time: 338 µs


### Most common erros in DL

- Shape Errors

In [49]:
tensor_A = torch.tensor([
        [1,2],
        [3,4],
        [5,6]
])

tensor_B = torch.tensor([
        [7,8],
        [8,11],
        [9,12]
])

In [50]:
torch.matmul(tensor_A,tensor_B.view(2,3))

tensor([[ 29,  26,  32],
        [ 65,  60,  72],
        [101,  94, 112]])

In [51]:
tensor_A.T, tensor_A

(tensor([[1, 3, 5],
         [2, 4, 6]]),
 tensor([[1, 2],
         [3, 4],
         [5, 6]]))

#### Transporse switches the axes of an tensor

In [52]:
tensor_B.T,tensor_B

(tensor([[ 7,  8,  9],
         [ 8, 11, 12]]),
 tensor([[ 7,  8],
         [ 8, 11],
         [ 9, 12]]))

### Finding the Min Max Mean and SUm of Tensors

In [53]:
x = torch.arange(0,100,10)

In [54]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [55]:
x.min()

tensor(0)

In [56]:
x.max()

tensor(90)

In [57]:
# requires a tensor of float or complex types
x.type(torch.float32).mean()

tensor(45.)

In [58]:
x.sum()

tensor(450)

### Finding the positional min and max

In [59]:
x.argmax()

tensor(9)

In [60]:
x.argmin()

tensor(0)

## Reshaping, stacking, squeezing, unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memeory as the orgiiganl tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeezing - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped in a certain way)


In [61]:
x = torch.arange(1,10)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
x.shape

torch.Size([9])

In [63]:
x_reshape = x.reshape(1,9)

In [64]:
x_reshape

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [65]:
z = x.view(1,9)

In [66]:
z.shape

torch.Size([1, 9])

In [67]:
x.shape

torch.Size([9])

In [68]:
# view shares the same memory
z[0][0] = 5
z,x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [69]:
# Stack tensors on top
x_stacked = torch.stack([x,x,x,x],dim=1)

In [70]:
x_stacked

tensor([[5, 5, 5, 5],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [71]:
# torch.squeeze() remove all 1 dimensional shape

In [72]:
x_reshape

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [73]:
x_reshape.shape

torch.Size([1, 9])

In [74]:
x_reshape.squeeze().shape

torch.Size([9])

In [75]:
x_squeezed = x_reshape.squeeze()

In [76]:
x_squeezed.unsqueeze(dim=0)

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [77]:
# premute - changes the dimensions of a tensors

In [78]:
x_original = torch.rand(size=(224,224,3)) #height, width ,color channels

In [79]:
torch.permute(x_original,(2,0,1)).shape, x_original.shape

(torch.Size([3, 224, 224]), torch.Size([224, 224, 3]))

### Indexing

Indexing with pytorch is similar with numpy

In [80]:
# Create a tensor

x = torch.arange(1,10).reshape(1,3,3)

In [81]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [82]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [83]:
x[0][0]

tensor([1, 2, 3])

In [84]:
x[0][0][0]

tensor(1)

In [85]:
x[0][2][2]

tensor(9)

In [86]:
x[:,:,2]

tensor([[3, 6, 9]])

## Pytorch tensors & Numpy

NumPy is a popular scientifica python numeical computing library

And becase of this Pytorch has functionalty to interact with it

* Data in Numpy, want in pytorch tensor -> `torch.from_numpy(ndarry)`
* Pytorch tensors -> Numpy `torch.Tensor.numpy()`

In [100]:
# NumPy array to tensor
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) # when converting from numpy, pyotrch reflects numpy's default datatype of float64
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [101]:
tensor.dtype

torch.float64

In [102]:
array = array +1

In [105]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()

In [106]:
numpy_tensor,tensor

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([1., 1., 1., 1., 1., 1., 1.]))

## Reproducibility (trying to take random out of random)

In short how a neural netowrk learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**

Essentially what the random seed does is flavor the randomness. It makes it constant

In [120]:
random_A = torch.rand(3,4)
random_B = torch.rand(3,4)

print(random_A)
print(random_B)
print(random_A == random_B)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [122]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_A = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_B = torch.rand(3,4)

print(random_A)
print(random_B)
print(random_A == random_B)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Accessing GPU

GPUs= faster computation on numbers, thanks to CUDA + NVIDIA hardware + Pytorch working BTS 

In [123]:
torch.cuda.is_available()

True