In [1]:
import torch
x = torch.Tensor([5,3])
y = torch.Tensor([2,1])
print(x*y)

tensor([10.,  3.])


In [2]:
x = torch.zeros([2,5])

In [3]:
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [4]:
x.shape

torch.Size([2, 5])

In [6]:
x.reshape(10)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
y = torch.rand([2,5])