In [1]:
!nvidia-smi

Fri Mar 12 13:18:34 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.56       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   60C    P8    31W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

# In this notebook we are going to cover some of the most fundamental conceps of tensorflow (tensors)

More specifically, we're going to cover: 
- Introduction to tensors
- Getting information from tensors
- Maniuplating tensors
- Tensors & Numpy
- Using @tf.funtion(Speed up python funtions)
- Using GPUs with Tensorflow(or TPU)
- Exercies

## Intro to tensors

In [2]:
# Import tensorflow
import tensorflow as tf
print(f"Version - {tf.__version__}")

Version - 2.4.1


In [3]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# Check the number of dimentions of tensors (ndmin = number of dimensions)
scalar.ndim

0

In [5]:
# Create a vector
vector = tf.constant([10,10])
vector
# shape 2 = num of stuff
# shape 1 = amount of arrays in there
# Not sure

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
# Check the dimentions of our vector
vector.ndim

1

In [7]:
# Create a matrix (more than 1 dimension)
matrix = tf.constant([[10,7],[7,10]])

In [8]:
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [9]:
matrix.ndim

2

In [10]:
# Create a another matrix
another_matrix = tf.constant([[10.0,7.0],[3.0,6.0],[56.0,85.0]],dtype=tf.float16)

In [11]:
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  6.],
       [56., 85.]], dtype=float16)>

In [12]:
another_matrix.ndim # another of stuff in arrays

2

In [13]:
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [14]:
tensor.ndim # amount of stuff in shape

3

This is known as a rank 3 tensor (3-dimensions), however a tensor can have an arbitrary (unlimited) amount of dimensions.

For example, you might turn a series of images into tensors with shape (224, 224, 3, 32), where:

224, 224 (the first 2 dimensions) are the height and width of the images in pixels.
3 is the number of colour channels of the image (red, green blue).
32 is the batch size (the number of images a neural network sees at any one time).
All of the above variables we've created are actually tensors. But you may also hear them referred to as their different names (the ones we gave them):

scalar: a single number.
vector: a number with direction (e.g. wind speed with direction).
matrix: a 2-dimensional array of numbers.
tensor: an n-dimensional arrary of numbers (where n can be any number, a 0-dimension tensor is a scalar, a 1-dimension tensor is a vector).
To add to the confusion, the terms matrix and tensor are often used interchangably.

Going forward since we're using TensorFlow, everything we refer to and use will be tensors.

### Creating tensors with `tf.Variable()`

In [15]:
# Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])

In [16]:
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [17]:
unchangeable_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [18]:
# Lets try and change one of the elements in a changeable tensor
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [19]:
# To numpy
changeable_tensor.numpy(),unchangeable_tensor.numpy()

(array([10,  7], dtype=int32), array([10,  7], dtype=int32))

In [20]:
unchangeable_tensor.numpy()[0]

10

In [21]:
# Try to assign
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [22]:
# Unchngeable tensor

# unchangeable_tensor[0].assign(7)
# unchangeable_tensor 
# Error

In [23]:
# Tf.contstant is better than tf.variable

### Creating random tensors

Random tensors are tensors of some abitrary size which contain random numbers

In [24]:
num = 9+11+11+12+5+11+13+10+6+9+6+9+2+5+4+5+10+2.5+15
num/60

2.591666666666667

In [25]:
# Create 2 random tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for to reporoduce 
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape=(3,2))
# Are they equal ? 
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False, False],
       [False, False]])>

### Shuffle data in tensors

In [26]:
# pandas.sample(frac=1) *In Pandas*

In [27]:
# Shuffle a tensor (valuable for when you want to shuffle the data so the inherent order doesnt effect learning)
not_shuffled = tf.constant([[10.0,7.0],[3.0,6.0],[56.0,85.0]])

In [28]:
not_shuffled.ndim

2

In [29]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[10.,  7.],
       [ 3.,  6.],
       [56., 85.]], dtype=float32)>

In [30]:
# Shuffle non-shuffled tensor
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[10.,  7.],
       [ 3.,  6.],
       [56., 85.]], dtype=float32)>

It looks like if we want our shuffled tensor to be in the same order we have to use the gloabal and operation level random seed

In [31]:
tf.random.set_seed(42) # gloabal random seed
tf.random.shuffle(not_shuffled,seed=42) # operation level random seed

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[10.,  7.],
       [ 3.,  6.],
       [56., 85.]], dtype=float32)>

In [32]:
tf.random.shuffle(not_shuffled,seed=42) # operation level random seed

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[56., 85.],
       [10.,  7.],
       [ 3.,  6.]], dtype=float32)>

## Other ways to make tensors

In [33]:
tf.zeros((1,25),tf.float32)

<tf.Tensor: shape=(1, 25), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [34]:
tf.ones((1,25),tf.float32)

<tf.Tensor: shape=(1, 25), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

### Turn numpy arrays into tensors

The main difference between Numpy array and tensorflow tensors. the tensorflow tensors can be run on the GPU

In [35]:
# Numpy array to tensorflow tensors
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32)
numpy_A
# Capaital for matrix or tensor
# Not capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [36]:
A = tf.constant(numpy_A,shape=(2,3,4)) # 2 * 3 * 4 = 24 (len(numpy_A))

In [37]:
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [38]:
A.ndim

3

### Getting information with tensors.

* Shape
* Rank
* Axis
* Size

In [39]:
tensor = tf.constant([0,1],dtype=tf.int8)

In [40]:
# Shape
tensor.shape

TensorShape([2])

In [41]:
# Axis (1) = 1 | (2,3) = 2 | (3,4,5) = 3
tensor.ndim

1

In [42]:
# Size (flaot/int)
tf.size(tensor)
# tf.size(tensor).dtype # get the exact size

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [43]:
tensor[0].numpy()

0

In [44]:
tensor[1].numpy()

1

In [45]:
# Get various attributes of our tensor
print('Datatype of every element : ', tensor.dtype)
print('Number of dimnsion (rank) : ',tensor.ndim)
print('Shape of tensor : ',tensor.shape)
print('Number of elements : ',tf.size(tensor).numpy())

Datatype of every element :  <dtype: 'int8'>
Number of dimnsion (rank) :  1
Shape of tensor :  (2,)
Number of elements :  2


 ### Indexing tensors
 
 Tensors can be indexed just like Python lists.

In [46]:
some_list = [1,2,3,4]
some_list[:2]#,:2,:2,:2]

[1, 2]

In [47]:
 some_list[:1]

[1]

In [48]:
 rank_4_tensor = tf.zeros([2,3,4,5])

In [49]:
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [50]:
rank_2_tensor = tf.constant([[10,7],[3,4]])

In [51]:
rank_2_tensor.shape

TensorShape([2, 2])

In [52]:
rank_2_tensor.ndim

2

In [53]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [54]:
some_list

[1, 2, 3, 4]

In [55]:
rank_2_tensor[:,-1].numpy()

array([7, 4], dtype=int32)

In [56]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[: , : , tf.newaxis]

In [57]:
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [58]:
# Alternative
tf.expand_dims(rank_2_tensor,axis=-1) # Final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [59]:
tf.expand_dims(rank_2_tensor,axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

### Manipulating tensors (tensor operations)

**Basic Operations** (+,-,*,/) (Python)

In [60]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[10,7],[3,4]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [61]:
tensor*2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 14],
       [ 6,  8]], dtype=int32)>

In [62]:
tensor/2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5. , 3.5],
       [1.5, 2. ]])>

In [63]:
tensor-5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5,  2],
       [-2, -1]], dtype=int32)>

In [64]:
# We can use the tensorflow built-in funtion
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [65]:
tf.add(tensor,5)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[15, 12],
       [ 8,  9]], dtype=int32)>

In [66]:
tf.subtract(tensor,5)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5,  2],
       [-2, -1]], dtype=int32)>

#### Matrix Multiplication

In machine learning, matrix multiplication is one of the mosr used tensor operations

There are 2 rules our tensors (or matrixces) need to fulfil :

1. Inner dimensions must match
2. The resulting matrox has the shape of the inner dimensions

In [67]:
# Matrix Multi
print(tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


In [68]:
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [69]:
tensor*tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [70]:
ex_1_tensor = tf.constant([
                           [1,2,1],
                           [0,1,0],
                           [2,3,4]
])
ex_2_tensor = tf.constant([
                           [2,5],
                           [6,7],
                           [1,8]
])

In [71]:
ex_1_tensor.numpy()

array([[1, 2, 1],
       [0, 1, 0],
       [2, 3, 4]], dtype=int32)

In [72]:
tf.matmul(ex_1_tensor,ex_2_tensor)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[15, 27],
       [ 6,  7],
       [26, 63]], dtype=int32)>

In [73]:
# Matrix multi with Python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [74]:
tensor.shape

TensorShape([2, 2])

In [75]:
# Create a tensor (3,2)
X = tf.constant([[1,2],[3,4],[5,6]])
y = tf.constant([[7,8],[9,10],[11,12]])

In [76]:
X

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [77]:
y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [78]:
# tf.matmul(X,y) # Error # The fliped one cant fit http://matrixmultiplication.xyz/

In [79]:
X

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [80]:
y.numpy().reshape(3,2)

array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)

In [81]:
X @ y.numpy().reshape(2,3)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

**The Dot product**

Matrix multi is also reggered to as the dot product.

* `tf.matmul()`
* `tf.tensordot()`
* `@`

In [82]:
# Perform the dot product on X and y (requires X or y to vbe transposed)
tf.tensordot(tf.transpose(X),y,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [83]:
# Perfrom matrix multiplciation between X and y (transposed)
tf.matmul(X,tf.transpose(y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [84]:
tf.matmul(X,tf.reshape(y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [85]:
print(f'Normal Y')
print(y)
print('\n')
print(f'Y reshaped to (2,3)')
print(tf.reshape(y,(2,3)))
print('\n')
print(f'Y trainsposed')
print(tf.transpose(y))

Normal Y
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)


Y reshaped to (2,3)
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32)


Y trainsposed
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [86]:
tf.matmul(X,tf.transpose(y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [87]:
# reshape is better

### Changing datatype of tensors

In [88]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.7,7.4])
B.dtype

tf.float32

In [89]:
C = tf.constant([7,10])
C.dtype

tf.int32

In [90]:
tf.__version__

'2.4.1'

In [91]:
# Change from float32 to float16 (reduced precision)
# 16 Bit Dtypes are Faster
D = tf.cast(B, dtype=tf.float16)
D

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [92]:
E = tf.cast(C, dtype=tf.int8)
E

<tf.Tensor: shape=(2,), dtype=int8, numpy=array([ 7, 10], dtype=int8)>

### Agreating tensor

Aggreating tensors = condensing then from multiple values down to smaller amount of values

In [93]:
# Get the absoulute values
D = tf.constant([-7,10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-7, 10], dtype=int32)>

In [94]:
# Get the absoulute values
abs(D) # turn all to positive

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [95]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Lets go through the following forms of aggresgation:
* Get the max
* Get the min
* Get the mean
* Get the sum

In [96]:
max(D)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [97]:
min(D)

<tf.Tensor: shape=(), dtype=int32, numpy=-7>

In [98]:
tf.reduce_mean(D)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [99]:
sum(D)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [100]:
tf.reduce_min(D)

<tf.Tensor: shape=(), dtype=int32, numpy=-7>

In [101]:
tf.reduce_max(D)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [102]:
tf.reduce_mean(D)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [103]:
np.min(D)

-7

In [104]:
np.max(D)

10

In [105]:
np.mean(D)

1.5

In [106]:
np.min(D)

-7

In [107]:
# tf.math.reduce_std(D)

In [108]:
import tensorflow_probability as tfp
tfp.stats.variance(D)

<tf.Tensor: shape=(), dtype=int32, numpy=72>

In [109]:
# Find standard deviation
tf.math.reduce_std(tf.cast(D,dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=8.5>

In [110]:
tf.math.reduce_variance(tf.cast(E,tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=2.25>

In [111]:
# TypeError : turn to float or int try it - TypeError: Input must be either real or complex

### Find the position maximum and min

In [112]:
# import numpy as np
# np.random.seed(42)

In [113]:
# Create a new tensor for finsing positional min and max
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [114]:
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [115]:
# Find the position max
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [116]:
# Find the position min
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [117]:
np.argmax(F)

42

In [118]:
np.argmin(F)

16

In [119]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [120]:
# Find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [121]:
# Find the min value of F
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [122]:
if F[tf.argmax(F)] == tf.reduce_max(F):
  print('Yes')
else:
  print('No')

Yes


### Squeezing a tensor (removing all singe dimensions)

In [123]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))

In [124]:
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [125]:
G_s = tf.squeeze(G)

### One hot encode a tensor

In [126]:
some_list = [0,1,2,3] # COULD BE RED GREEN BLUE PURPLE
# One hot encode our list of indices
tf.one_hot(some_list,len(some_list))

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [127]:
# Specifiy custom vals
tf.one_hot(some_list,depth=4,on_value='Whats poppin',off_value='Hey !!')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Whats poppin', b'Hey !!', b'Hey !!', b'Hey !!'],
       [b'Hey !!', b'Whats poppin', b'Hey !!', b'Hey !!'],
       [b'Hey !!', b'Hey !!', b'Whats poppin', b'Hey !!'],
       [b'Hey !!', b'Hey !!', b'Hey !!', b'Whats poppin']], dtype=object)>

### Squaring,log,square root

In [128]:
H = tf.range(1,10)

In [129]:
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [130]:
# Square
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [131]:
# Sqrt
tf.sqrt(tf.cast(H,tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828, 3.   ],
      dtype=float16)>

In [132]:
# Log
tf.math.log(tf.cast(H,tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 , 2.08  ,
       2.197 ], dtype=float16)>

### Tensors and numpy

TensorFlow interacts with Numpy arrays

In [133]:
# Create a tensor directly from a Numpy Array
J = tf.constant(np.array([5,6,8]))

In [134]:
J

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([5, 6, 8])>

In [135]:
J.numpy()

array([5, 6, 8])

In [136]:
np.array(J)

array([5, 6, 8])

In [137]:
type(J)

tensorflow.python.framework.ops.EagerTensor

In [138]:
type(J.numpy())

numpy.ndarray

In [139]:
J = tf.constant([3])

In [140]:
J.numpy()

array([3], dtype=int32)

In [141]:
# The default types of each
numpy_J = tf.constant(np.array([3,7,10]))
tensorflow_J = tf.constant([3,7,10])

In [142]:
numpy_J.dtype

tf.int64

In [143]:
tensorflow_J.dtype

tf.int32

### Finding access to GPUs

In [144]:
tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


True

In [145]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [146]:
tf.test.is_built_with_cuda()

True

In [147]:
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [148]:
!nvidia-smi

Fri Mar 12 13:18:47 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.56       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   61C    P0    72W / 149W |    125MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [150]:
!pip3 install wandb

     |████████████████████████████████| 2.0MB 5.5MB/s 
     |████████████████████████████████| 102kB 9.8MB/s 
     |████████████████████████████████| 133kB 39.0MB/s 
     |████████████████████████████████| 163kB 29.7MB/s 
     |████████████████████████████████| 71kB 8.3MB/s 
  Created wheel for pathtools: filename=pathtools-0.1.2-cp37-none-any.whl size=8786 sha256=161b0a712acb00b20dc6025782821f558357d9bd1746e3483aa40a19bc533453
  Stored in directory: /root/.cache/pip/wheels/0b/04/79/c3b0c3a0266a3cb4376da31e5bfe8bba0c489246968a68e843
  Created wheel for subprocess32: filename=subprocess32-3.5.4-cp37-none-any.whl size=6489 sha256=bf0e8f12008c1896b957d23b65ef1b17454504f5181cceb3080dcce098fe7f13
  Stored in directory: /root/.cache/pip/wheels/68/39/1a/5e402bdfdf004af1786c8b853fd92f8c4a04f22aad179654d1
Successfully built pathtools subprocess32
